// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	snp "github.com/andrii-minchekov/lets-go/domain/snippet"
	mock "github.com/stretchr/testify/mock"

	usr "github.com/andrii-minchekov/lets-go/domain/user"
)

// UseCases is an autogenerated mock type for the UseCases type
type UseCases struct {
	mock.Mock
}

// CreateSnippet provides a mock function with given fields: snippet
func (_m *UseCases) CreateSnippet(snippet snp.Snippet) (int64, error) {
	ret := _m.Called(snippet)

	var r0 int64
	if rf, ok := ret.Get(0).(func(snp.Snippet) int64); ok {
		r0 = rf(snippet)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(snp.Snippet) error); ok {
		r1 = rf(snippet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSnippet provides a mock function with given fields: id
func (_m *UseCases) GetSnippet(id int64) (*snp.Snippet, error) {
	ret := _m.Called(id)

	var r0 *snp.Snippet
	if rf, ok := ret.Get(0).(func(int64) *snp.Snippet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snp.Snippet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestSnippets provides a mock function with given fields:
func (_m *UseCases) LatestSnippets() (snp.Snippets, error) {
	ret := _m.Called()

	var r0 snp.Snippets
	if rf, ok := ret.Get(0).(func() snp.Snippets); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(snp.Snippets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignInUser provides a mock function with given fields: email, password
func (_m *UseCases) SignInUser(email string, password string) (int, error) {
	ret := _m.Called(email, password)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignupUser provides a mock function with given fields: user
func (_m *UseCases) SignupUser(user usr.User) (int, error) {
	ret := _m.Called(user)

	var r0 int
	if rf, ok := ret.Get(0).(func(usr.User) int); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(usr.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
