// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// hashComparator is an autogenerated mock type for the hashComparator type
type hashComparator struct {
	mock.Mock
}

// Execute provides a mock function with given fields: hash, text
func (_m *hashComparator) Execute(hash []byte, text []byte) error {
	ret := _m.Called(hash, text)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(hash, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
