// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	context "context"

	generated "github.com/andrii-minchekov/lets-go/app/impl/grpc"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// SnippetServiceClient is an autogenerated mock type for the SnippetServiceClient type
type SnippetServiceClient struct {
	mock.Mock
}

// CreateSnippet provides a mock function with given fields: ctx, in, opts
func (_m *SnippetServiceClient) CreateSnippet(ctx context.Context, in *generated.CreateSnippetRequest, opts ...grpc.CallOption) (*generated.CreateSnippetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *generated.CreateSnippetResponse
	if rf, ok := ret.Get(0).(func(context.Context, *generated.CreateSnippetRequest, ...grpc.CallOption) *generated.CreateSnippetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.CreateSnippetResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *generated.CreateSnippetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
