// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	context "context"

	boil "github.com/volatiletech/sqlboiler/v4/boil"

	mock "github.com/stretchr/testify/mock"

	models "github.com/andrii-minchekov/lets-go/app/impl/db/models"
)

// UserHook is an autogenerated mock type for the UserHook type
type UserHook struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *UserHook) Execute(_a0 context.Context, _a1 boil.ContextExecutor, _a2 *models.User) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, boil.ContextExecutor, *models.User) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
